name: zhaoxwing-sync
on:
  schedule:
    - cron: '6 */6 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-F1-Script
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync F1-Script
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://gitee.com/zhaoxwing/mytv/master.git"
          source_branch: "master"
          destination_branch: "zhaoxwing"
          github_token: ${{ secrets.PAT }}
